---
- name: Install ca package on rhel systems
  ansible.builtin.yum:
    name: ca-certificates
    state: present
  when: ansible_os_family == "RedHat"

- name: Install ca package on debian systems
  ansible.builtin.apt:
    name: ca-certificates
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Enable dynamic ca configuration on rhel6
  ansible.builtin.command: /bin/update-ca-trust enable
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6

- name: Update trusted ca debian
  ansible.builtin.command: /usr/sbin/update-ca-certificates
  when: ansible_os_family == "Debian"

- name: Update trusted ca redhat
  ansible.builtin.command: /bin/update-ca-trust
  when: ansible_os_family == "RedHat"
